package com.homefix.auth.emailauth;

import java.time.Duration;
import java.util.Optional;

import org.springframework.stereotype.Component;

import com.homefix.auth.config.EmailAuthProperties;
import com.homefix.auth.emailauth.EmailCodeStore.StoredCode;
import com.homefix.auth.otp.OtpCodeGenerator;

/**
 * Issues and checks emailed 6-digit codes, and throttles the requests that send them (email-auth
 * Requirements 1.8, 3.3, 8.1; Properties EA1 and EA2).
 *
 * <p>Codes are generated by {@link OtpCodeGenerator} ({@code SecureRandom}) and stored only as a
 * hash salted with their purpose and subject. A code is single-use, expires after the configured
 * lifetime, and is spent after the configured number of wrong attempts.
 *
 * <p>Every throttle here is applied before the caller looks anything up, and to every address alike,
 * so a 429 never says whether an address has an account.
 */
@Component
public class EmailCodes {

    private static final int CODE_LENGTH = 6;
    private static final Duration HOUR = Duration.ofHours(1);

    private final EmailCodeStore store;
    private final OtpCodeGenerator generator;
    private final EmailAuthProperties properties;

    public EmailCodes(EmailCodeStore store, OtpCodeGenerator generator, EmailAuthProperties properties) {
        this.store = store;
        this.generator = generator;
        this.properties = properties;
    }

    /**
     * Throttles emails to one address: one per cooldown, at most the hourly cap.
     *
     * @throws EmailAuthException 429 {@code TOO_MANY_REQUESTS} with the wait
     */
    public void requireSendAllowed(String email) {
        String key = "send:" + email;
        if (!store.tryStartCooldown(key, properties.getResendCooldown())) {
            long wait = Math.max(1, store.cooldownRemaining(key).getSeconds());
            throw EmailAuthException.tooManyRequests(wait);
        }
        if (store.countInWindow("send-hour:" + email, HOUR) > properties.getMaxCodesPerEmailPerHour()) {
            throw EmailAuthException.tooManyRequests(HOUR.getSeconds());
        }
    }

    /**
     * Throttles one kind of public request from one client IP (Requirement 8.1). A request with no
     * known address is not counted.
     *
     * @throws EmailAuthException 429 {@code TOO_MANY_REQUESTS}
     */
    public void requireIpAllowed(String action, String clientIp) {
        if (clientIp == null || clientIp.isBlank()) {
            return;
        }
        if (store.countInWindow("ip:" + action + ":" + clientIp, HOUR) > properties.getMaxRequestsPerIpPerHour()) {
            throw EmailAuthException.tooManyRequests(HOUR.getSeconds());
        }
    }

    /**
     * Creates a code for {@code (purpose, subject)}, replacing any earlier one.
     *
     * @param payload stored with the code and handed back by {@link #consume}; may be null
     * @return the code, to be emailed and then forgotten
     */
    public String issue(CodePurpose purpose, String subject, String payload) {
        String code = generator.generate(CODE_LENGTH);
        store.saveCode(purpose, subject, new StoredCode(hash(purpose, subject, code), 0, payload),
                properties.getCodeTtl());
        return code;
    }

    /**
     * Spends a code if {@code submitted} is right.
     *
     * @return the payload stored with the code, if any
     * @throws EmailAuthException 410 {@code CODE_EXPIRED} when there is no live code (never sent,
     *                            expired, used, or spent by wrong attempts); 400
     *                            {@code INVALID_CODE} for a wrong code, with the attempts left
     */
    public Optional<String> consume(CodePurpose purpose, String subject, String submitted) {
        StoredCode stored = store.findCode(purpose, subject).orElseThrow(EmailAuthException::codeExpired);
        int max = properties.getMaxCodeAttempts();
        if (stored.attempts() >= max) {
            store.deleteCode(purpose, subject);
            throw EmailAuthException.codeExpired();
        }
        if (submitted != null && generator.matches(submitted.strip(), salt(purpose, subject), stored.codeHash())) {
            // Only the request that removes the code may use it: two concurrent correct submissions
            // cannot both succeed.
            if (!store.deleteCode(purpose, subject)) {
                throw EmailAuthException.codeExpired();
            }
            return Optional.ofNullable(stored.payload());
        }
        int attempts = store.incrementAttempts(purpose, subject);
        if (attempts >= max) {
            store.deleteCode(purpose, subject);
        }
        throw EmailAuthException.invalidCode(Math.max(0, max - attempts));
    }

    public Duration codeTtl() {
        return properties.getCodeTtl();
    }

    private String hash(CodePurpose purpose, String subject, String code) {
        return generator.hash(code, salt(purpose, subject));
    }

    private static String salt(CodePurpose purpose, String subject) {
        return purpose.name() + ":" + subject;
    }
}
